### ISSUE TITLE
ライセンスを教えてください

### ISSUE THREAD

**Issue by veriserve2** [tarob19/UIUnityRenderer#1]
このソースコードを二次利用したいのですが、利用する場合のオープンソースライセンスはどうなりますか？
教えてください。

**Comment by tarob19** [comment]
ライセンス指定がなく、ご不便をお掛けして申し訳ありません。
改めてMITライセンスとして指定させていただきました。

**Comment by veriserve2** [comment]
回答ありがとうございます。
